### ISSUE TITLE
插件加载报错

### ISSUE THREAD

**Issue by laoxue** [bookfere/Send-to-Kindle-Calibre-Plugin#1]
calibre, version 6.11.0
错误： 未处理的异常: <b>InvalidPlugin</b>:The plugin in 'C:\\Users\\jonX\\Downloads\\Send-to-Kindle-Calibre-Plugin-master.zip' is invalid. It does not contain a top-level __init__.py file

calibre 6.11  embedded-python: True
Windows-10-10.0.19041-SP0 Windows ('64bit', 'WindowsPE')
('Windows', '10', '10.0.19041')
Python 3.10.1
Windows: ('10', '10.0.19041', 'SP0', 'Multiprocessor Free')
Interface language: zh_CN
Successfully initialized third party plugins: New Douban Books (1, 1, 0)
Traceback (most recent call last):
  File "calibre\gui2\preferences\plugins.py", line 325, in add_plugin
  File "calibre\customize\ui.py", line 479, in add_plugin
  File "calibre\customize\ui.py", line 64, in load_plugin
  File "calibre\customize\zipplugin.py", line 298, in load
  File "calibre\customize\zipplugin.py", line 393, in _locate_code
calibre.customize.InvalidPlugin: The plugin in 'C:\\Users\\jonX\\Downloads\\Send-to-Kindle-Calibre-Plugin-master.zip' is invalid. It does not contain a top-level __init__.py file

**Comment by laoxue** [comment]
> 

直接从github下载的zip 直接加载会报错，从其他取到下载的版本没问题

**Comment by bookfere** [comment]
谢谢反馈。GitHub 提供的下载 ZIP 功能会包含子文件夹，这会导致 Calibre 无法识别插件，现在手动添加了插件文件到 [Release 页面](https://github.com/bookfere/Send-to-Kindle-Calibre-Plugin/releases)，从这里下载就不会有问题了。
