### ISSUE TITLE
老版本不支持？4.19使用了下，依然是拼音

### ISSUE THREAD

**Issue by JaceeDai** [bookfere/Send-to-Kindle-Calibre-Plugin#5]

**Comment by bookfere** [comment]
谢谢反馈，问题已在提交 e57861e85fcddded1344d784e3c1d4cc4306520c 中修复，请试用 [v1.1.1 ](https://github.com/bookfere/Send-to-Kindle-Calibre-Plugin/releases/tag/v1.1.1) 版本。
