### ISSUE TITLE
1.1版本对老版本支持不好，我的Calibre3.48版本使用1.0版本可以正常使用

### ISSUE THREAD

**Issue by Lanmer** [bookfere/Send-to-Kindle-Calibre-Plugin#7]
1.1版本对老版本支持不太好，我的Calibre3.48版本使用1.0版本可以正常使用，但1,1版本无法发挥效果，发送的书在kindle中仍以拼音命名。

**Comment by bookfere** [comment]
谢谢反馈，根据你提供的细节信息，找到了问题所在，现在问题已在提交 e57861e85fcddded1344d784e3c1d4cc4306520c 中修复，请试用 [v1.1.1 ](https://github.com/bookfere/Send-to-Kindle-Calibre-Plugin/releases/tag/v1.1.1) 版本。
